/*************************************************************************
 * 
 *  Copyright 2009 by Giuseppe Castagno beppec56@openoffice.org
 *  
 *  The Contents of this file are made available subject to
 *  the terms of European Union Public License (EUPL) version 1.1
 *  as published by the European Community.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the EUPL.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  EUPL for more details.
 *
 *  You should have received a copy of the EUPL along with this
 *  program.  If not, see:
 *  https://www.osor.eu/eupl, http://ec.europa.eu/idabc/eupl.
 *
 ************************************************************************/

#ifndef __it_plio_ext_oxsit_security_cert_CertificateStateConditions_idl__
#define __it_plio_ext_oxsit_security_cert_CertificateStateConditions_idl__

  module it { module plio { module ext { module oxsit { module security { module cert {

/** State of a Certificate, for string display
 */
	enum CertificateStateConditions
	{
		/** The certificate revocation is not yet verified.
		 */
		REVOCATION_NOT_YET_CONTROLLED,
 
		/** The certificate revocation was verified.
		 */
		REVOCATION_CONTROLLED_OK,

		/** The certificate revocation control is not enabled
		 */
		REVOCATION_CONTROL_NOT_ENABLED,

		/** The CRL (Certificate Revocation List) cannot be accessed
		 */
		CRL_CANNOT_BE_ACCESSED,

		/** The CRL (Certificate Revocation List) cannot be verified against the IssuerDN and Issuer certificate
		<p>Usually this happens when the CA is not in the list of available CA.</p>
		 */
		CRL_CANNOT_BE_VERIFIED,

		/** The OCSP (On-line Certificate Status Protocol) server cannot be accessed against the IssuerDN and Issuer certificate
		<p>Usually this happens when the CA is not in the list of available CA.</p>
		 */
		OCSP_CANNOT_BE_ACCESSED,

		/**	Internet access is not enabled (working off-line).
		*/
		INET_ACCESS_NOT_ENABLED,

		/**	Internet cannot be accessed.
		*/
		INET_ACCESS_ERROR,

		/** Last state (maximum state).
		*/
		LAST_STATE
	}; 
 
  }; }; }; }; };  };
 
#endif
