/*************************************************************************
 * 
 *  Copyright 2009 by Giuseppe Castagno beppec56@openoffice.org
 *  
 *  The Contents of this file are made available subject to
 *  the terms of European Union Public License (EUPL) version 1.1
 *  as published by the European Community.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the EUPL.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  EUPL for more details.
 *
 *  You should have received a copy of the EUPL along with this
 *  program.  If not, see:
 *  https://www.osor.eu/eupl, http://ec.europa.eu/idabc/eupl.
 *
 ************************************************************************/

#ifndef __it_plio_ext_oxsit_security_cert_CertificateState_idl__
#define __it_plio_ext_oxsit_security_cert_CertificateState_idl__

  module it { module plio { module ext { module oxsit { module security { module cert {

/** State of a Certificate, for string display
 */
	enum CertificateState
	{
		/** The certificate was not verified.
		 */
		NOT_YET_VERIFIED,

		/** The certificate was verified, it's ok.
		 */
		OK,

		/** The certificate has expired.
		 */
		EXPIRED, 

		/** The certificate was revoked.
		 */
		REVOKED, 

		/** The certificate was revoked.
		 */
		SUSPENDED, 

		/** The certificate is not yet active.
		 */
		NOT_ACTIVE, 
		
		/** The certificate has some extension in a state not as required by
		compliance.
		*/
		ERROR_IN_EXTENSION,

		/** The certificate is malformed, internal structure seems broken.
		*/
		MISSING_EXTENSION,

		/** The certificate is not consistent with the requested standard.
		 */
		NOT_COMPLIANT,
 
		/** The certificate is malformed, internal does not conform to the requests.
		*/
		CORE_CERTIFICATE_ELEMENT_INVALID,

		/** The certificate appears wrongly signed or
		 */
		CA_CERTIFICATE_SIGNATURE_INVALID, 

		/** The certificate cannot be verified.
		 */
		NOT_VERIFIABLE, 

		/** The certificate is malformed, internal structure seems broken.
		*/
		MALFORMED_CERTIFICATE,

		/** Last state (maximum state).
		*/
		LAST_STATE
	}; 
 
  }; }; }; }; };  };
 
#endif
