/*************************************************************************
 * 
 *  Copyright 2009 by Giuseppe Castagno beppec56@openoffice.org
 *  
 *  The Contents of this file are made available subject to
 *  the terms of European Union Public License (EUPL) version 1.1
 *  as published by the European Community.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the EUPL.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  EUPL for more details.
 *
 *  You should have received a copy of the EUPL along with this
 *  program.  If not, see:
 *  https://www.osor.eu/eupl, http://ec.europa.eu/idabc/eupl.
 *
 ************************************************************************/

#ifndef __it_plio_ext_oxsit_security_cert_CertificationAuthorityState_idl__
#define __it_plio_ext_oxsit_security_cert_CertificationAuthorityState_idl__

  module it { module plio { module ext { module oxsit { module security { module cert {

/** State of a Certificate Authority (after control)
 */
	enum CertificationAuthorityState
	{
		/** the Certificate Authority still to be checked.
		 */
		NOT_YET_CHECKED,

		/** the Certificate Authority status cannot be checked.
		 */
		CANNOT_BE_CHECKED,

		/** the Certificate Authority it's nonreliable (not accredited).
		 */
		UNRELIABLE,

		/** the Certificate Authority was verified, it's reliable (accredited).
		 */
		CREDITED,

		/** the Certificate Authority was verified, it's accredited but there are errors.
		 */
		CREDITED_WITH_WARNING,

		/** The CA DB thumbprint was not checked.
		 */
		CA_LIST_DB_THUMBP_NOT_CHECKED, 
 
		/** The CA certificate is not consistent with the requested standard.
		 */
		NOT_COMPLIANT, 
 
		/** The root certificate is missing
		 */
		CA_LIST_DB_MISSING,
 
		/** Last state (maximum state).
		*/
		LAST_STATE
	}; 
 
  }; }; }; }; };  };
 
#endif
