/*************************************************************************
 * 
 *  Copyright 2009 by Giuseppe Castagno beppec56@openoffice.org
 *  
 *  The Contents of this file are made available subject to
 *  the terms of European Union Public License (EUPL) version 1.1
 *  as published by the European Community.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the EUPL.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  EUPL for more details.
 *
 *  You should have received a copy of the EUPL along with this
 *  program.  If not, see:
 *  https://www.osor.eu/eupl, http://ec.europa.eu/idabc/eupl.
 *
 ************************************************************************/

#ifndef __it_plio_ext_oxsit_security_cert_XOX_QualifiedCertificate_idl__
#define __it_plio_ext_oxsit_security_cert_XOX_QualifiedCertificate_idl__

#include <com/sun/star/util/DateTime.idl>
#include <com/sun/star/uno/Exception.idl>
#include <com/sun/star/lang/IllegalArgumentException.idl>
#include "XOX_CertificateExtension.idl"
#include "CertificateState.idl"
#include "CertificateAuthorityState.idl"
#include "XOX_CertificationPathControlProcedure.idl"
#include "XOX_CertificateComplianceControlProcedure.idl"

  module it { module plio { module ext { module oxsit { module security { module cert {

/** Interface of a Qualified X509 Certificate
<p>The certificate accessed through this interface can only be created in two ways:</p>
<p>by instantiating an AvailableSSCDs service and callig the scanDevices() method of its
XOX_AvailableSSCDs interface or</p>
<p>by opening an ODF document that contains one it it in its XAdES signature.</p>
<p>See service QualifiedCertificate for details.</p>
 */
	interface XOX_QualifiedCertificate 
	{
		/** the DER encoded form of the certificate.
		 */
		[attribute] sequence< byte > DEREncoded ;
		/** the state of the certificate, for general and string indications.
		<p>It's an integer in the form of <type scope="it::plio::ext::module::oxsit::security::cert">CertificateState</type>, the numerical value,
		not the enum (e.g. CertificateState.OK_value).</p>
		
	 	*/
		/* @see it::plio::ext::module::oxsit::security::cert::CertificateState
		*/
		[attribute, readonly] long CertificateState;
		/** conditions observed in checking the certificate state
		*/
		[attribute, readonly] long CertificateStateConditions;
		/** the state of the CA (certificate Authority) control.
	 	*/
		[attribute, readonly] long CertificationAuthorityState;
		/** the object used to control the certification path of this certificate
		*/
		[attribute, readonly] it::plio::ext::oxsit::security::cert::XOX_CertificationPathControlProcedure CertificateCertificationPathControl;

		/** the object used to control the certificate compliance
		*/
		[attribute, readonly] it::plio::ext::oxsit::security::cert::XOX_CertificateComplianceControlProcedure CertificateComplianceControl;

		/** the human readable rapresentation of the holder (subject) of this certificate.
		<p>This string is formed from the SubjectDN certificate field in the following way:</p>
		<p>If givenName and surname both exist, they are used togeter to form a string in the form of
		givenName+" "+surname</p>
		<p>if they both don't exist, then the commonName attribute is used</p>
		<p>if common name doesn't exist, then pseudonym is used</p>
		<p>If nothing of this exists, the entire subjectDN file is returned, same as for SubjectName below.</p>
	 	*/
		[attribute, readonly] string SubjectDisplayName ;
		/** the human readable representation of the version number attribute of the certificate.
	 	*/
		[attribute, readonly] string Version ;
		/** the human readable rapresentation of the serial number attribute of the certificate.
		 */
		[attribute, readonly] string SerialNumber ;
		/** The short version of the issuer name
		*/
		[attribute, readonly] string IssuerDisplayName ;
		/** the full issuer name attribute of the certificate.
		 */
		[attribute, readonly] string IssuerName ;
		/** the full subject name attribute of the certificate.
		*/
		[attribute, readonly] string SubjectName ;
		/** the validity NotBefore date attribute of the certificate.
		 */
		[attribute, readonly] string NotValidBefore ;
		/** the validity NotAfter date attribute of the certificate.
		 */
		[attribute, readonly] string NotValidAfter ;
		/** the human readable rapresentation of the algorithm of the subject public key
		 */
		[attribute, readonly] string SubjectPublicKeyAlgorithm;
		/** the human readable rapresentation of the value of the subject public key
		 */
		[attribute, readonly] string SubjectPublicKeyValue;
		/** the human readable rapresentation of the signature algorithm
		 */
		[attribute, readonly] string SignatureAlgorithm;
		/** the human readable rapresentation of the SHA1 thumbprint of the certificate.
		<p>It's computed by calculating the SHA1 digest of the DER encoded form of the entire certificate.</p>
		*/
		[attribute, readonly] string SHA1Thumbprint;
		/** the human readable rapresentation of the MD5 thumbprint of the certificate.
		<p>It's computed by calculating the MD5 digest of the DER encoded form of the entire certificate.</p>
		*/
		[attribute, readonly] string MD5Thumbprint;

		/** all the OIDs strings of the certificate extensions 
		*/
		[attribute, readonly] sequence<string> CertificateExtensionOIDs;

		/** all the OIDs strings of the certificate extensions marked critical 
		*/
		[attribute, readonly] sequence<string> CriticalCertificateExtensionOIDs;
		/** all the OIDs strings of the certificate extensions not marked critical
		*/
		[attribute, readonly] sequence<string> NotCriticalCertificateExtensionOIDs;

		/** The first certificate in the certification path, this is the start of the certification path
		tree.
		*/
		[attribute, readonly] it::plio::ext::oxsit::security::cert::XOX_QualifiedCertificate CertificationPath ;

		/** Returns all the critical extensions.
		<p></p>
		*/
		sequence<it::plio::ext::oxsit::security::cert::XOX_CertificateExtension> getCriticalExtensions();

		/** Returns all the Not critical extensions.
		<p></p>
		*/
		sequence<it::plio::ext::oxsit::security::cert::XOX_CertificateExtension> getNotCriticalExtensions();

		/** Find the localized name of an extension from OID.
		<p>the OID should be in string form, for example the string "2.5.29.15" for KeyUsage extension</p>
		*/
		string getCertificateExtensionName( [in] string oid ) ;

		/** Returns the human redeable content of an extension from OID.
		<p>the OID should be in string form, for example the string "2.5.29.15" for KeyUsage extension</p>
		*/
		string getCertificateExtensionStringValue( [in] string oid ) ;

		/** Returns the error state of an extension, in value of
		it.plio.ext.oxsit.security.cert.CertificateExtensionState.<>_value
		<p>the OID should be in string form, for example the string "2.5.29.15" for KeyUsage extension</p>
		<p>For the certificate item that don't have an OID, use the certificate element name; for example IssuerName will
		return the state of the check performed on issuerName element of TBSCertificate</p> 
		*/
		long getCertificateElementErrorState( [in] string oid ) ;

		/** Set the error state of an extension, in value of
		it.plio.ext.oxsit.security.cert.CertificateExtensionState.<>_value
		<p>the OID should be in string form, for example the string "2.5.29.15" for KeyUsage extension</p>
		*/
		void setCertificateElementErrorState( [in] string oid, [in] long newState) ;

		/** Set the interface objects used for the certificate compliance controlo procedure.
		<p>This interface is used internally at the end of the certificate preparation, inside setter method setDEREncoded().</p>
		<p>
		@see it::plio::oxsit::ext::security::cert::QualifiedCertificate
			For a description of the suggested method to use this interface.
		</p>
		*/
		void setCertificateComplianceControlObject([in] it::plio::ext::oxsit::security::cert::XOX_CertificateComplianceControlProcedure arg0)
						raises( ::com::sun::star::lang::IllegalArgumentException,
								::com::sun::star::uno::Exception );
		/** verify the Certificate Revocation List state of this 
		 certificate. Returns false if not OK, true if OK.
		 <p>Either cases, the CertificateState field will have the result.</p>
		 <p>The CertificateGraficStateValue field will have the result as well</p>
		*/
		boolean verifyCRLForCertificate( );

		/** Sets the interface object used to check for the certificate certification path.
		*/
		void setCertificationPathControlObject([in]  it::plio::ext::oxsit::security::cert::XOX_CertificationPathControlProcedure arg0)
						raises( ::com::sun::star::lang::IllegalArgumentException,
								::com::sun::star::uno::Exception );
		/** verify the Certification Path (e.g. the Certificate Authority) of this certificate. Returns false if not OK, true if OK.
		 <p>Either cases, the CertificationAuthorityState field will have the result.</p>
		 <p>The CertificateGraficStateValue field will have the result as well</p>
		  */
		boolean verifyCertificateCertificationPath( );
	} ;

  }; }; }; }; };  };
 
#endif
