/*************************************************************************
 * 
 *  Copyright 2009 by Giuseppe Castagno beppec56@openoffice.org
 *  
 *  The Contents of this file are made available subject to
 *  the terms of European Union Public License (EUPL) version 1.1
 *  as published by the European Community.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the EUPL.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  EUPL for more details.
 *
 *  You should have received a copy of the EUPL along with this
 *  program.  If not, see:
 *  https://www.osor.eu/eupl, http://ec.europa.eu/idabc/eupl.
 *
 ************************************************************************/

#ifndef __com_yacme_ext_oxsit_security_cert_XOX_DocumentSigner_idl__
#define __com_yacme_ext_oxsit_security_cert_XOX_DocumentSigner_idl__

#include <com/sun/star/lang/XComponent.idl>
#include <com/sun/star/uno/Exception.idl>
#include <com/sun/star/lang/IllegalArgumentException.idl>
#include <com/sun/star/uno/XComponentContext.idl> 
#include <com/sun/star/uno/XInterface.idl> 
#include <com/sun/star/embed/XStorage.idl> 
#include <com/sun/star/frame/XFrame.idl>
#include <com/sun/star/frame/XModel.idl>
#include "XOX_SignatureState.idl"
#include "CertificateState.idl"
#include "CertificateStateConditions.idl"
#include "XOX_X509Certificate.idl"

  module com { module yacme { module ext { module oxsit { module security {

/** Interface to implement document signer.
 */
	interface XOX_DocumentSigner
	{
	/** Used to remove the selected signature or all the signatures.<br>
		@param xFrame the frame to be used as anchor for dialogs
		@param xTheDocument the model of the document to be verified
		@param sSignatureUUID The UUID of the signature to be removed. If null all the signatures will be removed.
		@return true if the document can be signed, false otherwise.
		*/
	       boolean removeDocumentSignature([in] com::sun::star::frame::XFrame xFrame,
					       [in] com::sun::star::frame::XModel xTheDocumentModel,
					       [in] com::yacme::ext::oxsit::security::XOX_SignatureState sSignatureState )
		                     raises( ::com::sun::star::lang::IllegalArgumentException, ::com::sun::star::uno::Exception );

		/** Call this method to sign the document.<br>
		The method should implement itself the messages to the user, if they are necessary.
		@param xFrame the frame to be used as anchor for dialogs
		@param xTheDocument the model of the document to be signed
		@param xCertificates a sequence of certificates to use to sign the document.
		@param aArguments an array of UNO objects implementation dependent. Can be used to pass more arguments to the function
		@return true if the PIN was confirmed, false if the operation was cancelled
		*/
		boolean signDocument([in] com::sun::star::frame::XFrame xFrame,
									[in] com::sun::star::frame::XModel xTheDocumentModel,
						  			[in] sequence < com::yacme::ext::oxsit::security::cert::XOX_X509Certificate > xCertificates,
 									[in] sequence<any> aArguments )

						raises( ::com::sun::star::lang::IllegalArgumentException,
								::com::sun::star::uno::Exception );

		/** Used to check if the document can be signed, for example verify its content for presence of executable code (macro for example).<br>
		The method should implement itself the messages to the user, if they are necessary.<br>
		The method is called by the main implementation just before starting the dialog showing the list of certificate availables to sign (e.g. before
		exploring the SSCDs on the system).
		@param xFrame the frame to be used as anchor for dialogs
		@param xTheDocument the model of the document to be signed
		@param aArguments an array of UNO objects implementation dependent. Can be used to pass more arguments to the function
		@return true if the document can be signed, false otherwise.
		*/
		boolean verifyDocumentBeforeSigning([in] com::sun::star::frame::XFrame xFrame,
									[in] com::sun::star::frame::XModel xTheDocumentModel,
 									[in] sequence<any> aArguments )

						raises( ::com::sun::star::lang::IllegalArgumentException,
								::com::sun::star::uno::Exception );

	} ;

  }; }; }; }; };
 
#endif

