/*************************************************************************
 * 
 *  Copyright 2009 by Giuseppe Castagno beppec56@openoffice.org
 *  
 *  The Contents of this file are made available subject to
 *  the terms of European Union Public License (EUPL) version 1.1
 *  as published by the European Community.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the EUPL.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  EUPL for more details.
 *
 *  You should have received a copy of the EUPL along with this
 *  program.  If not, see:
 *  https://www.osor.eu/eupl, http://ec.europa.eu/idabc/eupl.
 *
 ************************************************************************/

#ifndef __com_yacme_ext_oxsit_security_cert_XOX_CertificatePKCS11Attributes_idl__
#define __com_yacme_ext_oxsit_security_cert_XOX_CertificatePKCS11Attributes_idl__

  module com { module yacme { module ext { module oxsit { module security { module cert {

/** 
<p>This interface to access the certificate attribute attribute on SSCDs</p>
  */
	interface XOX_CertificatePKCS11Attributes
	{
		/** the DER encoded form of the certificate.
		 */
		[attribute] sequence< byte > DEREncoded ;

		/** This is usually the CKA_LABEL of the certificate on SSCD
		*/
		[attribute] string Label ;

		/**
		*/
		[attribute] sequence < byte > ID ;
	}; 
 
  }; }; }; }; };  };
 
#endif
