/*************************************************************************
 * 
 *  Copyright 2009 by Giuseppe Castagno beppec56@openoffice.org
 *  
 *  The Contents of this file are made available subject to
 *  the terms of European Union Public License (EUPL) version 1.1
 *  as published by the European Community.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the EUPL.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  EUPL for more details.
 *
 *  You should have received a copy of the EUPL along with this
 *  program.  If not, see:
 *  https://www.osor.eu/eupl, http://ec.europa.eu/idabc/eupl.
 *
 ************************************************************************/

#ifndef __it_plio_ext_oxsit_security_cert_XOX_X509CertificateDisplay_idl__
#define __it_plio_ext_oxsit_security_cert_XOX_X509CertificateDisplay_idl__

#include <com/sun/star/lang/XComponent.idl>
#include <com/sun/star/util/DateTime.idl>
#include <com/sun/star/uno/Exception.idl>
#include <com/sun/star/lang/IllegalArgumentException.idl>
#include <com/sun/star/uno/XComponentContext.idl> 
#include <com/sun/star/frame/XFrame.idl>
#include <com/sun/star/text/XTextDocument.idl>
#include "CertificateElementID.idl"
#include "XOX_CertificateExtension.idl"

  module it { module plio { module ext { module oxsit { module security { module cert {

/** Interface of a X509 Certificate display data.
 */
	interface XOX_X509CertificateDisplay
	{
		/** the human readable rapresentation of the holder (subject) of this certificate.
		<p>This string is formed from the SubjectDN certificate field in the following way:</p>
		<p>If givenName and surname both exist, they are used togeter to form a string in the form of
		givenName+" "+surname</p>
		<p>if they both don't exist, then the commonName attribute is used</p>
		<p>if common name doesn't exist, then pseudonym is used</p>
		<p>If nothing of this exists, the entire subjectDN file is returned, same as for SubjectName below.</p>
	 	*/
		[attribute, readonly] string SubjectDisplayName ;
		/** the full subject name attribute of the certificate.
		*/
		[attribute, readonly] string SubjectName ;
		/** the human readable representation of the version number attribute of the certificate.
	 	*/
		[attribute, readonly] string Version ;
		/** the human readable rapresentation of the serial number attribute of the certificate.
		 */
		[attribute, readonly] string SerialNumber ;
		/** The short version of the issuer name
		*/
		[attribute, readonly] string IssuerDisplayName ;
		/** the full issuer name attribute of the certificate.
		 */
		[attribute, readonly] string IssuerName ;
		/** the full issuer name attribute of the certificate.
		 */
		[attribute, readonly] string IssuerCommonName ;
		/** the validity NotBefore date attribute of the certificate.
		 */
		[attribute, readonly] string NotValidBefore ;
		/** the validity NotAfter date attribute of the certificate.
		 */
		[attribute, readonly] string NotValidAfter ;
		/** the human readable rapresentation of the algorithm of the subject public key
		 */
		[attribute, readonly] string SubjectPublicKeyAlgorithm;
		/** the human readable rapresentation of the value of the subject public key
		 */
		[attribute, readonly] string SubjectPublicKeyValue;
		/** the human readable rapresentation of the signature algorithm
		 */
		[attribute, readonly] string SignatureAlgorithm;
		/** the human readable rapresentation of the SHA1 thumbprint of the certificate.
		<p>It's computed by calculating the SHA1 digest of the DER encoded form of the entire certificate.</p>
		*/
		[attribute, readonly] string SHA1Thumbprint;
		/** the human readable rapresentation of the MD5 thumbprint of the certificate.
		<p>It's computed by calculating the MD5 digest of the DER encoded form of the entire certificate.</p>
		*/
		[attribute, readonly] string MD5Thumbprint;

		/** all the OIDs strings of the certificate extensions 
		*/
		[attribute, readonly] sequence<string> CertificateExtensionOIDs;

		/** all the OIDs strings of the certificate extensions marked critical 
		*/
		[attribute, readonly] sequence<string> CriticalCertificateExtensionOIDs;
		/** all the OIDs strings of the certificate extensions not marked critical
		*/
		[attribute, readonly] sequence<string> NotCriticalCertificateExtensionOIDs;

		/** Returns all the critical extensions.
		<p></p>
		*/
		sequence<it::plio::ext::oxsit::security::cert::XOX_CertificateExtension> getCriticalExtensions();

		/** Returns all the Not critical extensions.
		<p></p>
		*/
		sequence<it::plio::ext::oxsit::security::cert::XOX_CertificateExtension> getNotCriticalExtensions();

		/** Find the localized name of an extension from OID.
		<p>the OID should be in string form, for example the string "2.5.29.15" for KeyUsage extension</p>
		*/
		string getCertificateElementLocalizedName( [in]  it::plio::ext::oxsit::security::cert::CertificateElementID  ElementID ) ;

		string getCertificateElementCommentString( [in] it::plio::ext::oxsit::security::cert::CertificateElementID  ElementID ) ;

		void setCertificateElementCommentString( [in] it::plio::ext::oxsit::security::cert::CertificateElementID  ElementID,
													[in] string aComment ) ;

		/** Find the localized name of an extension from OID.
		<p>the OID should be in string form, for example the string "2.5.29.15" for KeyUsage extension</p>
		*/
		string getCertificateExtensionLocalizedName( [in] string oid ) ;

		/** Returns the human redeable content of an extension from OID.
		<p>the OID should be in string form, for example the string "2.5.29.15" for KeyUsage extension</p>
		*/
		string getCertificateExtensionValueString( [in] string oid ) ;

		/** Returns an additional comment of a certificate from OID or the element description.<br>
		This comment can contains any character string suitable for a text document report generation.<br>
		A comment about the certificate core elements can be retrieved using as name parameter the name of the
		corresponding  attribute.<br>
		For example using "NotValidAfter" string will return a comment about the NotValidAfter element of the
		certificate.
		<p>the name should be in string form, for example the string "2.5.29.15" for KeyUsage extension.</p>
		*/
		string getCertificateExtensionCommentString( [in] string name ) ;

		/** The counterpart of getCertificateElementCommentString
		@param name
		@param comment
		*/
		void setCertificateExtensionCommentString( [in] string name, [in] string comment ) ;

		/** generate a report in a stand alone Writer document
		*/
		void generateCertificateReport([in] com::sun::star::lang::XComponent xCertificate)
						raises( ::com::sun::star::lang::IllegalArgumentException,
								::com::sun::star::uno::Exception );

		/** generate a report and add it to the document represented by the passed XTextDocument interface.
		@param aTextDocument
		*/
		void addCertificateReport([in] com::sun::star::text::XTextDocument aTextDocument,
									[in] com::sun::star::lang::XComponent xCertificate )
						raises( ::com::sun::star::lang::IllegalArgumentException,
								::com::sun::star::uno::Exception );

		/**
		@param xCertificate a UNO component supporting the XOX_X509Certificate interface.
		*/
		void prepareDisplayStrings([in] com::sun::star::frame::XFrame xFrame,
									[in] com::sun::star::lang::XComponent xCertificate)
						raises( ::com::sun::star::lang::IllegalArgumentException,
								::com::sun::star::uno::Exception );
	} ;

  }; }; }; }; };  };
 
#endif
