/*************************************************************************
 * 
 *  Copyright 2009 by Giuseppe Castagno beppec56@openoffice.org
 *  
 *  The Contents of this file are made available subject to
 *  the terms of European Union Public License (EUPL) version 1.1
 *  as published by the European Community.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the EUPL.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  EUPL for more details.
 *
 *  You should have received a copy of the EUPL along with this
 *  program.  If not, see:
 *  https://www.osor.eu/eupl, http://ec.europa.eu/idabc/eupl.
 *
 ************************************************************************/

#ifndef __it_plio_ext_oxsit_security_cert_XOX_CertificationPathControlProcedure_idl__
#define __it_plio_ext_oxsit_security_cert_XOX_CertificationPathControlProcedure_idl__

#include <com/sun/star/lang/XComponent.idl>

  module it { module plio { module ext { module oxsit { module security { module cert {

/** Interface of a Qualified X509 Certificate
<p>The certificate accessed through this interface can only be created in two ways:</p>
<p>by instantiating an AvailableSSCDs service and callig the scanDevices() method of its
XOX_AvailableSSCDs interface or</p>
<p>by opening an ODF document that contains one it it in its XAdES signature.</p>
<p>See service QualifiedCertificate for details.</p>
 */
	interface XOX_CertificationPathControlProcedure 
	{
		/** control the certification path of the UNO component passed as a parameter.
			the XComponent passed as a paremeter must have the XOX_QualifiedInterface available
			for executing the function. 
		  */
		long verifyCertificateCertificationPath([in] com::sun::star::lang::XComponent xCertificate);
	} ;

  }; }; }; }; };  };
 
#endif
