/*************************************************************************
 * 
 *  Copyright 2009 by Giuseppe Castagno beppec56@openoffice.org
 *  
 *  The Contents of this file are made available subject to
 *  the terms of European Union Public License (EUPL) version 1.1
 *  as published by the European Community.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the EUPL.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  EUPL for more details.
 *
 *  You should have received a copy of the EUPL along with this
 *  program.  If not, see:
 *  https://www.osor.eu/eupl, http://ec.europa.eu/idabc/eupl.
 *
 ************************************************************************/

#ifndef __it_plio_ext_oxsit_security_cert_XOX_SSCDevice_idl__
#define __it_plio_ext_oxsit_security_cert_XOX_SSCDevice_idl__

#include "XOX_X509Certificate.idl"

  module it { module plio { module ext { module oxsit { module security {

	/** this interface represents the main interface to hold data
	  of a single SSCD element on system (called token).
	  <p>The attributes described here can be retrieved using getters, for example the QualifiedCertificates attribute can be retrieved using:</p>
	  <p>getQualifiedCertificates(), which returns a sequence of XOX_QualifiedCertificate objects.</p>
	  <p>It needs to be expanded</p>
	 */
  interface XOX_SSCDevice
  {
		/** a description of the device
		*/
		[attribute] string Description;

		/** name of the manufacturer
		*/
		[attribute] string Manufacturer;

		/** the returned ATR code, (if this is a smart card, to be seen when it's something else)
		*/
		[attribute] string ATRcode;

		/** the low level crypto library used
		*/
		[attribute] string CryptoLibraryUsed;

		/** The number of available certificate on the token
		*/
		[attribute,readonly]  long HasX509Certificates;

		/** The certificates this device contains.
		*/
		[attribute,readonly]  sequence<it::plio::ext::oxsit::security::cert::XOX_X509Certificate> X509Certificates;

		/** Adds this certificate to the list of certificates available on this token.
		@param DERencoded the DER encoded byte array of the certificate to add.
		*/
		void	addCertificate( [in] sequence< byte > DERencoded);
//		void	addAQualifiedCertificate( [in] it::plio::ext::oxsit::security::cert::XOX_X509Certificate aCertificate);
  };
 
  }; }; }; }; };
 
#endif
