
#ifndef __org_openoffice_test_OXDocumentSignatures_idl__
#define __org_openoffice_test_OXDocumentSignatures_idl__
#include <com/sun/star/uno/XInterface.idl>
//#include <com/sun/star/awt/Size.idl>
 
  module it { module plio { module ext { module oxsit { module ooo { module cert {
 
  interface OXDocumentSignatures : com::sun::star::uno::XInterface 
  {
      [attribute] string DocumentURL;
//      [attribute] string DestinationDirectory;
//      [attribute] com::sun::star::awt::Size Dimension;
  };
 
  }; }; }; }; };  };
 
#endif

